- managers/ChungWooJin.html
- Rename : JeongUjin.html to ChungWooJin.html
- Update  ChungWooJin.html
- Update profile
- 
- hi
- 
-
> Update and rename JeongUjin.html to ChungWooJin.html

- managers/HongYeeun.html
눈에 띄는거 위주로 수정했습니다.
HTML 본문 내용 수정
커밋 확인, 익명의 내용을 유저 내용 위주로 정정
테스트 필요하지 않음.
브랜치 컨벤션 없나요?
이상 있으면 태그주세요.
> Update HongYeeun.html, 내용 정정

- managers/LimYeram.html
- 임예람에 관한 내용 변경했습니다.
- 없습니다.
- 없습니다.
- 없습니다.
> update yeram's file info

- index.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> test: 천재지우기

- index.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> Test: commit 되돌리기

- members/KimHyeoksu.html
- 김혁수 페이지 수정
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> 김혁수 페이지 수정

- members/JangDojin.html
- 자기소개 내용 바꿨습니다,
- 이름이랑 기술 스택 확인 바라요 
- 내용을 적어주세요
- 내용을 적어주세요
> 테스트 입니다.-도진

- members/LeeNayeong.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> Baranchofme

- members/JungHasom.html
- 디저트39 흑임자라떼 강추~!!!!!!!
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> test: 테스트임니돠

- members/LeeHyeoncheol.html
- light weight baby
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat:이현철 입니다

- members/LeeSangyun.html
- 넵
- 수정 사항 반영했습니다.
- 잘 모르겠습니다.
- 멋사 화이팅!
- 없습니다.
> [11기 이상윤] Feat: 수정 사항 반영

- members/LeeGyeongji.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat: 이름 수정했습니다.

- members/KimHyeona.Html
김현아 정보수정함
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat: About 수정

- members/KimJunyeong.html
- 영문 이름으로 변경
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> kimjuneyoung으로 수정

- members/LimSeungmin.html
- 정보수정했습니다
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat: 정보 수정

- index.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> test: git rebase origin/main

- members/JungHasom.html
- 프사 바꿨어요!!!!
- 와웅~~~~
- 업데이트 해주세여~~~~
- 내용을 적어주세요
> 사진넣기 했어여!!!

- members/KimHyeona.Html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat: 영어이름으로 수정(현아)

- members/JungJaeung.html
- 영어이름으로 바꿨습니당
- 음
- 잘 부탁드립니다~~~~~
- 열심히 할게요!!!
> fix: Change Name English 정재웅

- members/LeeTaeyeon.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> docs:이름을영어로

- members/KimNayeon.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> Munzi 이름변경

- members/LeeNayeong.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> 진짜 최종 수정 바보x

- members/LeeDaeun.html
- 이름 수정했습니다
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat: 이름수정

- members/ShinWoosung.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat : 이름 수정

- members/LeeYebin.html
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
- 내용을 적어주세요
> feat: 이름 영문 수정
